CREATE TABLE snapshots (
  id SERIAL PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  table_name TEXT NOT NULL,
  snapshot_id TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL
);
